steps:
- target: body
  placement: center
  title: '<div><img class="rounded-lg" src="/static/images/prompts-tour-banner.svg" style="width: 100%; margin-bottom: 16px;"/><div class="text-28/36 text-primary-content">使用AI自动标注</div></div>'
  content: '<div style="width: 100%">我们为您设置了一个初始提示词，并提供了一些OpenAI积分，帮助您开始自动标注您的项目。<br/><br/>让我们带您了解一下！</div>'

- target: .cm-editor
  placement: right
  title: '<div style="color: var(--color-neutral-content-subtler)">步骤 1 of 3</div>'
  content: '<div style="width: 100%;">我们已经为您生成了一份提示词，基于您的项目标注配置。<br/><br/>请随意调整！</div>'

- target: '[data-testid="evaluate-model-button"]'
  placement: top
  title: '<div style="color: var(--color-neutral-content-subtler)">步骤 2 of 3</div>'
  content: '<div style="width: 100%;">保存后，点击这里开始获取任务的预测。</div>'

- target: body
  placement: center
  title: '<div class="text-28/36">🎉<br /><strong>就是这样！</strong></div>'
  content: '查看输出流，点击任何任务查看完整预测。<br/>一旦您准备好了，在<b>"所有项目任务"</b>上运行您的提示词，获取所有任务的预测！'
  locale:
    last: '完成'
